# To disable a field use "field = <ignored>"
[temperatureBind]
boiler_temperature = "post:{post_id}:boiler_temperature"
floor_heating_enabled = "post:{post_id}:floor_heating_enabled"
floor_heating_temperature = "post:{post_id}:floor_heating_temperature"
heating_wire_enabled = "post:{post_id}:heating_wire_enabled"
heating_wire_temperature = "post:{post_id}:heating_wire_temperature"
outdoor_temperature = "post:{post_id}:outdoor_temperature"
winter_mode_enabled = "post:{post_id}:winter_mode_enabled"
winter_mode_temperature = "post:{post_id}:winter_mode_temperature"

[dosingServiceState]
cycle_time = "post:{post_id}:cycle_time"
powder_dispencer_state = "post:{post_id}:powder_dispencer_state"
stroke_time = "post:{post_id}:stroke_time"

[lightingService]
is_manual_on = "post:{post_id}:is_manual_on"
is_constant_light_on = "post:{post_id}:di:is_constant_light_on"
is_twilight_sensor_on = "post:{post_id}:twilight_sensor"
manual_mode = "post:{post_id}:lighting:set:manual_mode"
schedule_mode = "post:{post_id}:lighting:set:schedule_mode"
sensor_mode = "post:{post_id}:lighting:set:sensor_mode"
start_hours = "post:{post_id}:lighting:start_hours"
start_minutes = "post:{post_id}:lighting:start_minutes"
stop_hours = "post:{post_id}:lighting:stop_hours"
stop_minutes = "post:{post_id}:lighting:stop_minutes"
follow_constant_mode = "post:{post_id}:lighting:set:follow_constant_mode"

[postLightSwitch]
post_light = "post:{post_id}:post_light"

[maintenanceBind]
circultaion_pump_state = "post:{post_id}:circultaion_pump_state"
circultaion_solenoid_state = "post:{post_id}:circultaion_solenoid_state"
phase_failure = "post:{post_id}:phase_failure"

[osmosLevels]
high_level = "post:{post_id}:osmos_high_level"
low_level = "post:{post_id}:osmos_low_level"
mid_level = "post:{post_id}:osmos_mid_level"
osmos_level = "post:{post_id}:osmos_osmos_level"

[osmosPressures]
current_pressure = "post:{post_id}:osmos_current_pressure"
min_pressure = "post:{post_id}:osmos_min_pressure"
start_pressure = "post:{post_id}:osmos_start_pressure"
stop_pressure = "post:{post_id}:osmos_stop_pressure"

[osmosActivations]
bypass_mode = "post:{post_id}:osmos_bypass_mode"
bypass_state = "post:{post_id}:osmos_bypass_state"
osmos_error = "post:{post_id}:osmos_osmos_error"
pressure_switch_state = "post:{post_id}:osmos_pressure_switch_state"
solenoid_state = "post:{post_id}:osmos_solenoid_state"
tower_pump_state = "post:{post_id}:osmos_tower_pump_state"

[osmosValvesSwitch]
pump = "post:{post_id}:osmos_pump"
valve = "post:{post_id}:osmos_valve"

[waterState]
current_pressure = "post:{post_id}:di:water_current_pressure"
high_pressure = "post:{post_id}:di:water_high_pressure"
low_pressure = "post:{post_id}:di:water_low_pressure"
max_pressure = "post:{post_id}:di:water_max_pressure"
min_pressure = "post:{post_id}:di:water_min_pressure"
water_pressure_alarm = "post:{post_id}:di:water_pressure_alarm"

[statsReset]
encashment_reset = "post:{post_id}:reset:encashment_reset"
full_finances_reset = "post:{post_id}:reset:full_finances_reset"
post_time_reset = "post:{post_id}:reset:post_time_reset"
pumps_time_reset = "post:{post_id}:reset:pumps_time_reset"


[washingProgram]
valves = "post:{post_id}:washing_program:{id}:valves"
dosing_valves = "post:{post_id}:washing_program:{id}:dosing_valves"
pumps = "post:{post_id}:washing_program:{id}:pumps"
cost = "post:{post_id}:washing_program:{id}:cost"

[pumpState]
is_running = "post:{post_id}:pump:{pump_id}:is_running"
last_service_run_hours = "post:{post_id}:pump:{pump_id}:last_service_run_hours"
last_service_run_seconds = "post:{post_id}:pump:{pump_id}:last_service_run_seconds"
last_service_time = "post:{post_id}:pump:{pump_id}:last_service_time"
mode = "post:{post_id}:pump:{pump_id}:mode"
oil_change_hours = "post:{post_id}:pump:{pump_id}:oil_change_hours"
operating_hours = "post:{post_id}:pump:{pump_id}:operating_hours"
operating_hours_from_last_service = "post:{post_id}:pump:{pump_id}:operating_hours_from_last_service"
run_hours_counter = "post:{post_id}:pump:{pump_id}:run_hours_counter"
run_seconds_counter = "post:{post_id}:pump:{pump_id}:run_seconds_counter"
service_hours = "post:{post_id}:pump:{pump_id}:service_hours"
service_mode = "post:{post_id}:pump:{pump_id}:service_mode"

[pumpControls]
is_on = "post:{post_id}:do:pump:{pump_id}"

[dosingValve]
state = "post:{post_id}:do:dosing_valve:{dosing_valve_id}"

[valveControls]
state = "post:{post_id}:do:valve:{id}"

[winterService]
winter_mode_enabled = "post:{post_id}:winter_mode"

[winterValve]
state = "post:{post_id}:do:winter_valve"