[parsing]
"{station_id}" = "16"

[localization]
time_zone = "UTC+02:00"

[[redis.servers]]
name = "local.1"
server_host = "127.0.0.1"
#host = "192.168.11.243"
server_port = 6300

[[redis.servers]]
name = "remote.1"
server_host = "127.0.0.1"
server_port = 7000

[[redis.streams]]
name = "stationlog"
mode = "producer"
target_server = "local.1"
stream_key = "station:{station_id}"
stream_size = 1000000 # producer only. '-1' to ignore

[[redis.streams]]
name = "commands_writer"
mode = "producer"
target_server = "local.1"
stream_key = "station:{station_id}:commands"
stream_size = 1000000 # producer only. '-1' to ignore

[[redis.streams]]
name = "station_reader"
mode = "consumer"
source_server = "local.1"
stream_key = "station:{station_id}"

[[redis.streams]]
name = "commandlog"
mode = "consumer"
source_server = "remote.1"
stream_key = "station:{station_id}:commands"

[[redis.streams]]
name = "commands_local"
mode = "consumer"
source_server = "local.1"
stream_key = "station:{station_id}:commands"

[[redis.caches]]
name = "modbuscache" #name_producer and name_consumer are created! REFACTOR THIS!
mode = "producer"
target_server_name = "local.1"
db_index = 0
index_key = "station:{station_id}:index"
consumers = [ "stationlog" ]

[websocket.server]
port = 1234
producers = [ "station_reader" ]
consumers = [ "commands_writer" ]

[websocket.client]
host = "10.40.0.88"
port = 8002
    
[log_debug]
modbus = true
mysql = false
websocket_server = true
websocket_client = true
