[lotos]
[lotos.worker]
name = "lotos"
debug = false
    [[lotos.posts]]
    worker.name = "post.1"
    worker.consumers = [ "modbus.master.post.1" , "modbus.master.post.1.di_do"]
    worker.producers = [ "modbus.master.post.1" , "modbus.master.post.1.di_do"]
    programs_count = 7
    pumps_count = 1
    dosing_valves_count = 4
    valves_count = 4
    redis_cache_worker = "posts.cache"
    washing_finish_timeout = 120 # seconds
    pump_oil_change_hours = 250
    pump_service_hours =  500
    services_update_rate =  5000
    constant_lighting_start_minutes = 540
    constant_lighting_stop_minutes = 1140
    [[lotos.posts]]
    worker.name = "post.2"
    worker.consumers = [ "modbus.master.post.2" , "modbus.master.post.2.di_do"]
    worker.producers = [ "modbus.master.post.2" , "modbus.master.post.2.di_do"]
    programs_count = 7
    pumps_count = 1
    dosing_valves_count = 4
    valves_count = 4
    redis_cache_worker = "posts.cache"
    washing_finish_timeout = 120 # seconds
    pump_oil_change_hours = 250
    pump_service_hours =  500
    services_update_rate =  5000
    constant_lighting_start_minutes = 540
    constant_lighting_stop_minutes = 1140