[[modbus.devices]]
    tcp.name = "post.1.china"
    tcp.host = "192.168.1.75"
    tcp.port = 502
[[modbus.devices]]
    tcp.name = "post.2.china"
    tcp.host = "192.168.1.76"
    tcp.port = 502
[[modbus.devices]]
    tcp.name = "gateway.1"
    tcp.host = "192.168.1.253"
    tcp.port = 502
[[modbus.devices]]
    tcp.name = "gateway.2"
    tcp.host = "192.168.1.254"
    tcp.port = 502


[[modbus.master]]
    slave_id = 1
    channel = 0
    register_names = ["post.1"]
    device_name = "gateway.1"
    worker.name = "modbus.master.post.1"
    queries = [ { reg_index = 0, reg_count = 12, type = "holding" },
                { reg_index = 12, reg_count = 12, type = "holding" } ]

[[modbus.master]]
    slave_id = 1
    channel = 2
    register_names = ["post.1.di", "post.1.do"]
    device_name = "post.1.china"
    worker.name = "modbus.master.post.1.di_do"
    queries = [ { reg_index = 0, reg_count = 4, type = "discrete_inputs" }]

[[modbus.master]]
    slave_id = 2
    channel = 0
    register_names = ["post.2"]
    device_name = "gateway.2"
    worker.name = "modbus.master.post.2"
    queries = [ { reg_index = 0, reg_count = 12, type = "holding" },
                { reg_index = 12, reg_count = 12, type = "holding" } ]

[[modbus.master]]
    slave_id = 1
    channel = 1
    register_names = ["post.2.di", "post.2.do"]
    device_name = "post.2.china"
    worker.name = "modbus.master.post.2.di_do"
    queries = [ { reg_index = 0, reg_count = 4, type = "discrete_inputs" }]