[[modbus.devices]]
    tcp.name = "slave.server"
    tcp.host = "0.0.0.0"
    tcp.port = 12502

[[modbus.slave]]
    worker.name = "modbus.navigard"
    device_name = "slave.server"
    slave_id = 1
    register_names = ["1111"]