[post.1]
__table__ = "holding"
led_status = { index = 0, type = "uint16" }
output_status = { index = 1, type = "uint16" }
watchdog = { index = 2, type = "uint16" }
washing_state = { index = 3, type = "uint16" }
last_pressed_index = { index = 4, type = "uint16" }
money.index = { index = 5, type = "uint16" }
money.credit_card = { index = 6, type = "uint16" }
money.coin = { index = 7, type = "uint16" }
money.key = { index = 8, type = "uint16" }
money.paper = { index = 9, type = "uint16" }
money.system = { index = 10, type = "uint16" }
program_index = { index = 11, type = "uint16" }
config = { index = 13, type = "uint16" }
stop_mode = { index = 14, type = "uint16" }
stop_time = { index = 15, type = "uint16" }
stop_speed = { index = 16, type = "uint16" }
credit_cost = { index = 17, type = "uint16" }
minute_costs = [ { index = 18, type = "uint16" },
                { index = 19, type = "uint16" },
                { index = 20, type = "uint16" },
                { index = 21, type = "uint16" },
                { index = 22, type = "uint16" },
                { index = 23, type = "uint16" },
                { index = 24, type = "uint16" } ]


[post.1.di]
__table__ = "discrete_inputs"
water_pressure_alarm = { index = 0, type = "uint16" }
phase_alarm = { index = 1, type = "uint16" }
osmos_alarm = { index = 3, type = "uint16" }
is_constant_light_on = { index = 2, type = "uint16" }

[post.1.do]
__table__ = "coils"
valve = [ { index = 0 },
           { index = 1 },
           { index = 2 },
           { index = 3 },
           { index = 4 } ]
winter_valve = { index = 5 }
pump.1 = {index = 6}
osmos_pump = { index = 7 }
post_lighting = { index = 8 }
dosing_valve = [ { index = 9 },
                  { index = 10 },
                  { index = 11 },
                  { index = 12 },
                  { index = 13 },
                  { index = 14 }]


[post.2]
__table__ = "holding"
led_status = { index = 0, type = "uint16" }
output_status = { index = 1, type = "uint16" }
watchdog = { index = 2, type = "uint16" }
washing_state = { index = 3, type = "uint16" }
last_pressed_index = { index = 4, type = "uint16" }
money.index = { index = 5, type = "uint16" }
money.credit_card = { index = 6, type = "uint16" }
money.coin = { index = 7, type = "uint16" }
money.key = { index = 8, type = "uint16" }
money.paper = { index = 9, type = "uint16" }
money.system = { index = 10, type = "uint16" }
program_index = { index = 11, type = "uint16" }
config = { index = 13, type = "uint16" }
stop_mode = { index = 14, type = "uint16" }
stop_time = { index = 15, type = "uint16" }
stop_speed = { index = 16, type = "uint16" }
credit_cost = { index = 17, type = "uint16" }
minute_costs = [ { index = 18, type = "uint16" },
                { index = 19, type = "uint16" },
                { index = 20, type = "uint16" },
                { index = 21, type = "uint16" },
                { index = 22, type = "uint16" },
                { index = 23, type = "uint16" },
                { index = 24, type = "uint16" } ]


[post.2.di]
__table__ = "discrete_inputs"
water_pressure_alarm = { index = 0, type = "uint16" }
phase_alarm = { index = 1, type = "uint16" }
osmos_alarm = { index = 3, type = "uint16" }
is_constant_light_on = { index = 2, type = "uint16" }

[post.2.do]
__table__ = "coils"
valve = [ { index = 0 },
           { index = 1 },
           { index = 2 },
           { index = 3 },
           { index = 4 } ]
winter_valve = { index = 5 }
pump.1 = {index = 6}
osmos_pump = { index = 7 }
post_lighting = { index = 8 }
dosing_valve = [ { index = 9 },
                  { index = 10 },
                  { index = 11 },
                  { index = 12 },
                  { index = 13 },
                  { index = 14 }]