pipelines:
  - api.websocket <=> repeater(api)
  - fountain.thin > *unwrap(modbus) > fountain.thin.modbus 
  - fountain.thin.modbus > *rename(running_frequency, speed) > *wrap(modbus) > fountain.thin
  - repeater(api) <=branch(fountains:0)=> fountain.thin

fountain_settings_common: &fountain_settings
  max_speed_value: 5000
  uptime:
    days: [1, 2, 3, 4, 5]
    start_hour: 9
    start_minute: 0
    stop_hour: 17
    stop_minute: 0
  scripts:
    default:
      time_per_step_ms: 3000
      data: [10, 40, 50, 60]

python:
  - worker:
      name: fountain.thin
      print_msgs: true
    module_path: fountain.py
    module_settings: *fountain_settings

modbus: !include modbus.yaml

websocket:
  servers:
    - worker:
        name: api.websocket
      port: 1234