pipelines:
  - api.websocket <=> repeater(api)
  - repeater(api) <=branch(fancoils:floor:2:switch:0)=block(regulators:1)=> fancoil.worker.floor.2.switch.0
  - fancoil.worker.floor.2.switch.0 < *temp.divide < fancoil.modbus.floor.2.switch.0
  - fancoil.worker.floor.2.switch.0 > *temp.mul > fancoil.modbus.floor.2.switch.0
  - fancoil.worker.floor.2.switch.0 > mock(plc.modbus) 

interceptors:
  validating:
    temp.divide:
      by_validator:
        divide_by(10): [temperature:current, temperature:target]
    temp.mul:
      by_validator:
        multiply_by(10): [temperature:current, temperature:target]

fancoil_common: &fancoil_common
  plc: 
    regulator_key: regulators:1
    low_speed: 500
    mid_speed: 800
    high_speed: 1000

python:
  - worker:
      name: fancoil.worker.floor.2.switch.0
      print_msgs: true
    module_path: fancoil.py
    module_settings: *fancoil_common

modbus: !include modbus.yaml

websocket:
  servers:
    - worker:
        name: api.websocket
      port: 1234