pipelines:
  - api.websocket <=> repeater(api)
  - repeater(api) <=branch(fancoils:floor:2:switch:0)=block(regulators:1)=> fancoil.worker.floor.2.switch.0
  - fancoil.modbus.floor.2.switch.0 <=> fancoil.worker.floor.2.switch.0
  - fancoil.worker.floor.2.switch.0 > mock(plc.modbus) 
  - udp.in(3333) > fancoil.worker.floor.2.switch.0

fancoil_common: &fancoil_common
  plc: 
    regulator_key: regulators:1
    low_speed: 500
    mid_speed: 800
    high_speed: 1000

python:
  - worker:
      name: fancoil.worker.floor.2.switch.0
    module_path: fancoil.py
    module_settings: *fancoil_common

modbus: !include modbus.yaml

websocket:
  servers:
    - worker:
        name: api.websocket
      port: 1234